# Chat GPT question
GET http://localhost:3333/ask1/
Content-Type: application/json

{}

###

# Add Food to Database

POST http://localhost:3333/createFood/
Content-Type: application/json

{
    "name": "C",
    "amount": 200
}

###

# Get All Foods From Database

GET http://localhost:3333/foods/
Content-Type: application/json

{}