# Chat GPT question
GET http://localhost:3333/ask2/
Content-Type: application/json

{}

###

# Add Food to Database

POST http://localhost:3333/createFood/
Content-Type: application/json

{
    "name": "pão",
    "amount": "4 fatias"
}

###

# Get All Foods From Database

GET http://localhost:3333/foods/
Content-Type: application/json

{}